repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: \.html$|\.txt$
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
